#!/bin/bash

# test the github distribution in a container

# build the base container

docker build -t objiotest-base - <<EOF
FROM ubuntu:19.10
ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get install -qqy git
RUN apt-get install -qqy python3
RUN apt-get install -qqy python3-pip
RUN apt-get install -qqy python3-venv
RUN apt-get install -qqy curl
EOF

# run the test as a second stage build without caching

docker build -t objiotest --no-cache - <<EOF
FROM objiotest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/objio.git /tmp/objio
WORKDIR /tmp/objio
RUN python3 -m venv venv
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF
