#!/bin/bash
docker build -t objiotest-base - <<EOF
FROM ubuntu:19.10
ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get install -qqy git python3 python3-pip
EOF
docker build -t objiotest --no-cache - <<EOF
FROM objiotest-base
RUN pip3 install objio
RUN obj --help
EOF
