#!/usr/bin/python3
import sys
import objio
import typer

app = typer.Typer()

@app.command()
def cat(url, timeout:float=3600):
    """Cat the given object to stdout."""
    pipe = objio.objopen(url, verb="read", stream=sys.stdout.buffer)
    if pipe: pipe.wait(timeout)

@app.command()
def put(url, timeout:float=3600):
    """Upload stdin to the given location."""
    pipe = objio.objopen(url, verb="write", stream=sys.stdin.buffer)
    if pipe: pipe.wait(timeout)

@app.command()
def list(url, timeout:float=3600):
    """List the objects in the given bucket or at the given path."""
    pipe = objio.objopen(url, verb="list", stream=sys.stdout)
    if pipe: pipe.wait(timeout)

@app.command()
def auth(url, timeout:float=3600):
    """Authenticate to the server for the URL."""
    pipe = objio.objopen(url, verb="auth", stream=sys.stdout)
    if pipe: pipe.wait(timeout)

@app.command()
def buckets(url, timeout:float=3600):
    """List all available buckets for the currently authenticated user."""
    pipe = objio.objopen(url, verb="buckets", stream=sys.stdout)
    if pipe: pipe.wait(timeout)

if __name__ == "__main__":
    app()
